ProjetoOficina/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oficina.urls')),
    path('relatorios/', include('relatorios.urls')),
    path('account/', include('django.contrib.auth.urls')),
    #url(r'^$',views.singIn),
    #url(r'^postsign/',views.postsign)
]

oficina/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views
app_name = 'oficina'
urlpatterns = [
    path('', views.index, name='index'),   
    path('register/', views.register, name='register'),
    path('produtos/', views.produtos, name='produtos'),
    path('produtos/new/', views.novo_produto, name='novo_produto'),
    path('produtos/delete/<int:id>/', views.apagar_produto, name='apagar_produto'),
    path('produtos/update/<int:id>/', views.atualizar_produto, name='atualizar_produto'),
    path('produtos/validar/', views.validar_descricao_produto, name='validar_descricao_produto'),
    #####################################
    path('fornecedores/', views.fornecedores, name='fornecedores'),
    path('fornecedores/new', views.novo_fornecedor, name='novo_fornecedor'),
    path('fornecedores/delete/<int:id>/', views.apagar_fornecedor, name='apagar_fornecedor'),
    path('fornecedores/edit/<int:id>/', views.atualizar_fornecedor, name='atualizar_fornecedor'),
    #######################################
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/new', views.novo_cliente, name='novo_cliente'),
    path('clientes/edit/<int:id>/', views.atualizar_cliente, name='atualizar_cliente'),
    path('clientes/delete/<int:id>/', views.apagar_cliente, name='apagar_cliente'),
    #######################################
    path('servicos/', views.servicos, name='servicos'),
    path('servicos/new', views.novo_servico, name='novo_servico'),
    path('servicos/delete/<int:id>/', views.apagar_servico, name='apagar_servico'),
    path('servicos/edit/<int:id>/', views.atualizar_servico, name='atualizar_servico'),
    #######################################
    path('vendas/', views.vendas, name='vendas'),
    path('vendas/detail/<int:orcamento_id>/', views.detail_orcamento, name='detail_orcamento'),    
    path('orcamentos/', views.orcamentos, name='orcamentos'),
    path('orcamentos/delete/<int:id>/', views.apagar_orcamento, name='apagar_orcamento'),
    path('orcamentos/edit/<int:id>/', views.atualizar_orcamento, name='atualizar_orcamento'),
    path('vendas/new', views.nova_venda, name='nova_venda'),    
    path('vendas/add/item/<int:orcamento_id>/', views.novo_item, name='novo_item'),
    path('vendas/delete/item/<int:orcamento_id>/<int:id>/', views.apagar_item, name='apagar_item'),
    path('vendas/edit/item/<int:orcamento_id>/<int:id>/', views.atualizar_item, name='atualizar_item'),
    path('vendas/finish/<int:orcamento_id>/', views.finalizar_venda, name='finalizar_venda'),
]

oficina/models.py
from django.db import models
import datetime
class Categoria(models.Model):
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.nome
class Produto(models.Model):
    descricao = models.CharField(max_length=255,unique=True)
    quantidade = models.IntegerField()
    valor_compra = models.DecimalField(max_digits=9, decimal_places=2)
    valor_venda = models.DecimalField(max_digits=9, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    categoria = models.ForeignKey(to=Categoria, on_delete=models.CASCADE, blank=True, null=True)
    codigo_fabrica = models.IntegerField(blank=True, null=True)
    estoque_minimo = models.PositiveSmallIntegerField(blank=True, null=True,default=1)

    class Meta:
        ordering = ['descricao']

    def __str__(self):
        txt = '{} | QTD: {} | Preço: R${}'.format(self.descricao,self.quantidade,self.valor_venda)
        return txt

    def get_valor_venda(self):
        return self.valor_venda
    
    def baixar_estoque(self,quantidade):
        if (self.quantidade - quantidade) >= 0:        
            self.quantidade = self.quantidade - quantidade
            return True
        else:
            return False
    
    def get_estoque_baixo(self):
        if self.quantidade <= self.estoque_minimo:
            return True
            

class Endereco(models.Model):
    logradouro = models.CharField(max_length=255)
    numero = models.CharField(max_length=5)
    bairro = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    complemento = models.CharField(max_length=255, blank=True, null=True)
    ESTADOS_CHOICES = (
        ("AC","Acre"),("AL","Alagoas"),  ("AM","Amazonas"),("AP","Amapá"),("BA","Bahia"),("CE","Ceará"),("DF","Distrito Federal"),("ES","Espírito Santo"),("GO","Goiás"),("MA","Maranhão"),("MG","Minas Gerais"),("MS","Mato Grosso do Sul"),("MT","Mato Grosso"),("PA","Pará"),("PB","Paraíba"),("PE","Pernambuco"),("PI","Piauí"),("PR","Paraná"),("RJ","Rio de Janeiro"),("RN","Rio Grande do Norte"),("RO","Rondônia"),("RR","Roraima"),("RS","Rio Grande do Sul"),("SC","Santa Catarina"),("SE","Sergipe"),("SP","São Paulo"),("TO","Tocantins")
    )
    estado = models.CharField(max_length=2, choices=ESTADOS_CHOICES)

class Telefone(models.Model):
    telefone = models.CharField(max_length=255)    
    def get_id(self):
        return self.id
    def __str__(self):
        return self.telefone
        

class Fornecedor(models.Model):
    descricao = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=255, blank=True, null=True)
    endereco = models.OneToOneField(Endereco, on_delete=models.SET_NULL, null=True)
    observacao = models.CharField(max_length=255,blank=True, null=True)
    telefone = models.OneToOneField(Telefone,on_delete=models.SET_NULL,null=True)
    def get_endereco(self):
        return self.endereco.id
    def __str__(self):
        return self.descricao
    def get_telefone(self):
        return self.telefone.id

class Servico(models.Model):
    descricao = models.CharField(max_length=255)
    valor = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return self.descricao

class Cliente(models.Model):
    nome = models.CharField(max_length=255)
    cpf = models.CharField(max_length=255,blank=True, null=True)
    telefone = models.OneToOneField(Telefone, on_delete=models.SET_NULL, null=True)
    endereco = models.OneToOneField(Endereco, on_delete=models.SET_NULL, null=True)
    STATUS_CHOICES = (
        ("+","Positivo"),("-","Negativo"),("0","Nulo")
    )
    status = models.CharField(max_length=1,choices=STATUS_CHOICES,default="Nulo")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nome
    
    def get_endereco(self):
        return self.endereco.id
    def get_telefone(self):
        return self.telefone.id

class OrcamentoVenda(models.Model):
    TIPO_CHOICES = (
        ("DINHEIRO","DINHEIRO"),("CARTÂO","CARTÂO"),("PRAZO","PRAZO")
    )
    tipo = models.CharField(max_length=8, choices=TIPO_CHOICES, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE,blank=True, null=True)
    vendedor = models.CharField(max_length=255, null=True)
    status = models.BooleanField()    
    desconto = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)

    class Meta:
        ordering = ['-created']
    
    def numero_itens(self):       
       itens = ItemVenda.objects.filter(orcamento=self.id)
       total = 0
       for item in itens:
           total = total + item.quantidade
       return total

    def get_itens(self):
        return ItemVenda.objects.filter(orcamento=self.id)
        
    def get_itens_vendidos(self):
        if self.status:
            lista_itens = ItemVenda.objects.filter(orcamento=self.id)
            lista_final = []
            for item in lista_itens:
                if item.produto != None:
                    lista_final.append(item.produto.descricao)
                    #lista_final = lista_final + item.produto.descricao
            return lista_final

    def preco_total(self):
        if self.desconto == None:
            return self.get_preco_subtotal() - 0
        elif (self.get_preco_subtotal() - self.desconto) >= 0:
            return self.get_preco_subtotal() - self.desconto

    def get_preco_subtotal(self):
        itens = ItemVenda.objects.filter(orcamento=self.id)
        total = 0
        for item in itens:
            total = total + item.get_preco_total()
        return total
        
class Venda(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    orcamento = models.OneToOneField(OrcamentoVenda, on_delete=models.SET_NULL,null=True)

class ItemVenda(models.Model):
    servico = models.ForeignKey("Servico",on_delete=models.CASCADE,blank=True, null=True)
    produto = models.ForeignKey("Produto",on_delete=models.CASCADE,blank=True, null=True)    
    orcamento = models.ForeignKey("OrcamentoVenda",on_delete=models.CASCADE,blank=True, null=True)
    quantidade = models.IntegerField()
    
    def __str__(self):
        if self.servico != None:
            return str(self.servico)
        if self.produto != None:
            return str(self.produto)

    def get_preco_und(self):
        if self.produto != None:
            return (self.produto.valor_venda)
        elif self.servico != None:
            return (self.servico.valor)
            
    def get_preco_total(self):
        if self.produto != None:
            return (self.produto.valor_venda * self.quantidade)
        elif self.servico != None:
            return (self.servico.valor * self.quantidade)
        

'''
class ItemCaixa(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    despesa = models.CharField(max_length=255, null=True, blank=True)


class Caixa(models.Model):
    created = models.DateTimeField(auto_now_add=True)
'''

oficina/forms.py
from django import forms
from .models import *
from django_select2.forms import *

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ["descricao","quantidade","valor_compra","valor_venda","categoria","codigo_fabrica","estoque_minimo"]
        widgets = {
            'categoria': Select2Widget,            
        }

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ["descricao", "cnpj", "observacao"]

class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ["logradouro","numero","bairro","cidade","estado","complemento"]

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nome","cpf","status"]

class TelefoneForm(forms.ModelForm):
    class Meta:
        model = Telefone
        fields = ["telefone"]

class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ["descricao","valor"]

class OrcamentoVendaForm(forms.ModelForm):
    class Meta:
        model = OrcamentoVenda
        fields = ["tipo","cliente","vendedor","status","desconto"]
        
class ItemVendaForm(forms.ModelForm):
    class Meta:
        model = ItemVenda
        fields = ("servico","produto","quantidade",)
        
    
class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ["orcamento"]

oficina/templates/oficina/vendas/atualizarOrcamentoVenda.html
{% extends 'oficina/base.html'%}
{% block title %} Editar Venda | Hugo Moto Peças{% endblock %}
{% block css%} 
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
{% endblock%}
{% block content %}
    {% block javascript %}    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>     
        $(document).ready(function() {
            $('#id_tipo').select2();
        });
        $(document).ready(function() {
            $('#id_cliente').select2();
        });            
    </script>
    {% endblock %}
    {% load bootstrap %}
    <div class="card shadow mb-4" >        
        <div class="card-body">
        <form action="{{ request.get_full_path }}" method="POST">
            {% csrf_token %}
                                 
                <div class="col-sm-12">  
                    {{ form_orcamento.tipo|bootstrap }}
                </div>
                <div class="col-sm-12"> 
                    {{ form_orcamento.cliente|bootstrap }}
                </div>
                <div class="col-sm-12">
                    {{ form_orcamento.vendedor|bootstrap }}
                </div>
                <div class="col-sm-12">
                    {{ form_orcamento.desconto|bootstrap }}
                </div>
                <div style="margin-top:20px; float:right; margin-right:12px;">
                    <input type="submit" class="btn btn-primary mb-2" value="Continuar">
                </div>
            
        </form>  
        </div>  
    </div>   
    
{% endblock %}

oficina/templates/oficina/vendas/detail.html
{% extends 'oficina/base.html'%}
{% block title %}Detalhes Venda | Hugo Moto Peças{% endblock %}
{% block content %}    
{% load bootstrap %}
<div>
    
    <!-- Formulario da Venda-->
    <div class="card shadow mb-4" >        
        <div class="card-body">
            <div class="">                       
                <div class="row" style="margin-left:0px;">
                    <div class="col-sm">
                        Tipo de Pagamento
                        <input id="tipo_orcamento" class="form-control" type="text" placeholder="{{ orcamento.tipo }}" readonly>
                    </div>
                    <div class="col-sm">
                        Cliente
                        <input class="form-control" type="text" placeholder="{% if orcamento.cliente%} {{ orcamento.cliente }} {% endif%}" readonly>
                    </div>
                    <div class="col-sm">
                        Vendedor
                        <input class="form-control" type="text" placeholder="{{ orcamento.vendedor }}" readonly>
                    </div>                                                       
                </div>                                            
            </div>            
        </div>
    </div>
    
    </div>

    
    <!-- Tabela para mostrar todos itens de vendas no Orcamento -->
     
    <div class="table table-striped table-responsive">
        <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0">
            <thead class="thead-dark">
                <tr>                    
                <th class="">Descrição</th>
                <th class="">QTD</th>                    
                <th class="">Preço UND</th>
                <th class="">Total</th>                    
                </tr>
            </thead>
                
            <tbody>
                {% for item in lista_itens%}
                <tr>
                    {% comment %} <td>{{item}}</td> {% endcomment %}
                    <td>
                    {% if item.produto != None %}
                        {{item.produto.descricao}}
                    {% elif item.servico != None%}
                        {{item.servico.descricao}}
                    {% endif %}
                    </td>
                    <td>{{item.quantidade}}</td>
                    <td>R$ {{item.get_preco_und}}</td>    
                    <td>R$ {{item.get_preco_total}} </td>                                            
                </tr>
                {% endfor %}       
                
            </tbody>
        </table>
    </div>

    <!-- Div para o Valor total da Venda -->
    <div class="col-sm-12 card border shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">                        
                    <div class="text-xs font-weight-bold gray-100 text-uppercase mb-1" style="font-size:20px;">Subtotal</div>                            
                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1" style="font-size:20px;">Desconto</div>                            
                    
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1" style="font-size:20px;">Total</div>                        
                    
                </div>
                
                <div class="col-auto">
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">R$ {{ orcamento.get_preco_subtotal}}</div>
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">
                        R$ {% if orcamento.desconto %}{{ orcamento.desconto }}{% else%}0,00 {% endif%}
                    </div>                    
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">R$ {{ orcamento.preco_total}}</div> 
                </div>
                
            </div>
        </div>
    </div>

{% endblock %}

oficina/templates/oficina/vendas/novaVenda.html
{% extends 'oficina/base.html'%}
{% block title %} Nova Venda | Hugo Moto Peças{% endblock %}
{% block css%} 
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
{% endblock%}
{% block content %}
    {% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script>     
        $(document).ready(function() {
            $('#id_tipo').select2();
        });
        $(document).ready(function() {
            $('#id_cliente').select2();
        });            
    </script>
    {% endblock %}
    {% load bootstrap %}
    <div class="card shadow mb-4" >        
        <div class="card-body">
        <form action="{{ request.get_full_path }}" method="POST">
            {% csrf_token %}
                                 
                <div class="col-sm-12">  
                    {{ form_orcamento.tipo|bootstrap }}
                </div>
                <div class="col-sm-12"> 
                    {{ form_orcamento.cliente|bootstrap }}
                </div>
                <div class="col-sm-12">  
                    {% comment %} Vendedor
                    <input class="form-control" type="text" placeholder="{{ vendedor }}" readonly> {% endcomment %}
                    {{ form_orcamento.vendedor|bootstrap }}
                </div>
                <div style="margin-top:20px; float:right; margin-right:12px;">
                    <input type="submit" class="btn btn-primary mb-2" value="Continuar">
                </div>
            
        </form>  
        </div>  
    </div>  
    
{% endblock %}

oficina/templates/oficina/vendas/novoItemVenda.html
{% extends 'oficina/base.html'%}
{% block title %} Nova Venda | Hugo Moto Peças{% endblock %}
{% block css%} 
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
{% endblock%}
{% block content %}    
{% load bootstrap %}
<div>    
    <!-- Mensagem de erro se venda não for finalizada -->
    {% if msg_erro_finalizar %}
        <div class="alert alert-danger" role="alert" id="teste">
            {{msg_erro_finalizar}}
        </div>
    {% endif %}
    
    <!-- Formulario da Venda-->
    <div class="card shadow mb-4" >
        
        <div class="card-body">
            <div class="">                       
                <div class="row" style="margin-left:0px;">
                    <div class="col-sm">
                        Tipo de Pagamento
                        <input id="tipo_orcamento" class="form-control" type="text" placeholder="{{ orcamento.tipo }}" readonly>
                    </div>
                    <div class="col-sm">
                        Cliente
                        <input class="form-control" type="text" placeholder="
                            {% if orcamento.cliente%} {{ orcamento.cliente }} {% else %} Venda Avulsa {% endif%}"
                        readonly>
                    </div>
                    <div class="col-sm">
                        Vendedor
                        <input class="form-control" type="text" placeholder="{{ orcamento.vendedor }}" readonly>
                    </div>
                    <div class="col-1" style="margin-top:30px;">
                        <a href="{% url 'oficina:atualizar_orcamento' orcamento_id%}">
                         <img id="botao_enviar" src="https://img.icons8.com/color/35/000000/edit.png">
                        </a>
                    </div>                                       
                </div>
                <form action="{{ request.get_full_path }}" method="POST"> 
                    {% csrf_token %}   
                    <div class="row" style="margin-left:0px;">                         
                        <div class="col-sm-3">                     
                            {{ form.servico|bootstrap }}                                                            
                        </div>
                        <div class="col-sm-6">                              
                            {{ form.produto|bootstrap }}
                        </div>
                        <div class="col-sm-2">
                            {{ form.quantidade|bootstrap }}                                                            
                        </div>    
                        <div class="col-sm-1" style="margin-top:33px;">
                            <input type="image" src="https://img.icons8.com/color/35/000000/add.png" alt="Submit">                            
                        </div>                     
                    </div>
                </form>
                <!---->                
                <!---->
                <div class="row" style="margin-left:0px;">
                    <div class="col-sm">                    
                        <div class="text-xs font-weight-bold gray-100 text-uppercase mb-1" style="font-size:1 0px;">
                            <a href="{% url 'oficina:atualizar_orcamento' orcamento_id%}">
                                Adicionar Desconto                        
                                <img src="https://img.icons8.com/office/16/000000/add-tag.png">
                            </a>
                        </div>                    
                    </div>
                </div>                
            </div>            
        </div>
    </div>
    
    </div>

    <!-- Mensagem de erro se venda de produto ultrapassar estoque -->
    {% if msg_estoque_baixo %}
        <div class="alert alert-danger" role="alert" id="teste">
            {{msg_estoque_baixo}}
        </div>
    {% endif %}
    
    <!-- Tabela para mostrar todos itens de vendas no Orcamento -->
     
    <div class="table table-striped table-responsive">
        <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0">
            <thead class="thead-dark">
                <tr>                    
                <th class="">Descrição</th>
                <th class="">QTD</th>                    
                <th class="">Preço UND</th>
                <th class="">Total</th>
                <th class="">Ações</th>
                </tr>
            </thead>
                
            <tbody>
                {% for item in lista_itens%}
                <tr>
                    {% comment %} <td>{{item}}</td> {% endcomment %}
                    <td>
                    {% if item.produto != None %}
                        {{item.produto.descricao}}
                    {% elif item.servico != None%}
                        {{item.servico.descricao}}
                    {% endif %}
                    </td>
                    <td>{{item.quantidade}}</td>
                    <td>R$ {{item.get_preco_und}}</td>    
                    <td>R$ {{item.get_preco_total}} </td>                    
                    <td>
                        <a href="{% url 'oficina:atualizar_item' orcamento_id item.id%}"><img src="https://img.icons8.com/color/20/000000/edit.png"></a>
                        <a href="{% url 'oficina:apagar_item' orcamento_id item.id%}"><img src="https://img.icons8.com/color/20/000000/delete.png"></a>
                    </td>
                </tr>
                {% endfor %}       
                
            </tbody>
        </table>
    </div>


    <!-- Div para o Valor total da Venda -->
    <div class="col-sm-12 card border shadow">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">                        
                    <div class="text-xs font-weight-bold gray-100 text-uppercase mb-1" style="font-size:20px;">Subtotal</div>                            
                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1" style="font-size:20px;">Desconto</div>                            
                    
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1" style="font-size:20px;">Total</div>                        
                    
                </div>
                
                <div class="col-auto">
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">R$ {{ orcamento.get_preco_subtotal}}</div>
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">
                        R$ {% if orcamento.desconto %}{{ orcamento.desconto }}{% else%}0,00 {% endif%}
                    </div>                    
                    <div style="font-size:25px;" class="h5 mb-0 font-weight-bold text-gray-800">R$ {{ orcamento.preco_total}}</div> 
                </div>
                
            </div>
        </div>
    </div>

    <!-- Botões de Finalizar ou Excluir Venda -->
    <div style="margin-top:20px;">
        <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#finishModal">Finalizar Venda</button>        
    </div>

    <div style="margin-top:20px;margin-bottom:20px;">        
        <button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#cancelModal">Excluir Orçamento</button>
    </div>    


</div >

<!-- Div Para Mostar Mensagem de excluir Orcamento de venda -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deseja excluir esse orcamento?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecine "Sim" para excluir o orcamento.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Não</button>
          <a class="btn btn-primary" href="{% url 'oficina:apagar_orcamento' orcamento_id %}">Sim</a>
        </div>
      </div>
    </div>
</div> 

<!-- Div Para Mostar Mensagem de Finalizar venda -->

<div class="modal fade" id="finishModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deseja Finalizar a Venda?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecine "Sim" para Finalizar a Venda.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Não</button>
          <a class="btn btn-primary" href="{% url 'oficina:finalizar_venda' orcamento_id %}">Sim</a>
        </div>
      </div>
    </div>
</div>
{% endblock %}

oficina/templates/oficina/vendas/orcamentoVendas.html
{% extends 'oficina/base.html'%}
{% block title %}Vendas | Hugo Moto Peças{% endblock %}
{% load static %}
{% block css %} <link href="{% static 'oficina/css/search.css' %}" rel="stylesheet"> {% endblock %}
{% block content %}
    {% block javascript %} 
<script src="{% static 'oficina/js/functions/search.js' %}"></script>
<script src="{% static 'oficina/js/functions/sortTable.js' %}"></script>
{% endblock %}
  
  <!-- Search Bar-->
  <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Pesquise ..">

  <!-- Novo Orcamento -->
  <div style="float:right; margin-bottom:10px;">
    <a href="{% url 'oficina:nova_venda'%}">     
        <p class="text-xs font-weight-bold text-success text-uppercase mb-1" style="margin-left:15px; font-size:15px;"> 
            Nova 
            <img src="https://img.icons8.com/color/30/000000/add.png" alt="submit">
        </p>
    </a>
  </div>

  <!-- Tabela de Produtos -->
  <div class="table table-striped table-responsive">
    <table class="table table-bordered " id="myTable" width="100%" cellspacing="0">
      <tr class="header thead-dark" style="cursor:pointer;">
        <th onclick="sortTable(0)">Data</th>        
        <th onclick="sortTable(1)" id="">Cliente</th>
        <th onclick="sortTable(2)" id="">Vendedor</th>
        <th onclick="">QTD de Itens</th>
        <th onclick="">Tipo</th>
        <th onclick="sortTable(5)">Valor Total</th>
         <th onclick="">Status</th>
        <th>Ações</th>
      </tr>
      {% for orcamento in orcamentos %}
      <tr>
        <td style="font-size:12px;">{{ orcamento.modified }}</td>
        
        <td style="font-size:12px;">
        {% if orcamento.cliente%} {{ orcamento.cliente }} {% else %} Venda Avulsa {% endif%}
        </td>
        <td style="font-size:12px;">{{ orcamento.vendedor }}</td>
        <td>{{ orcamento.numero_itens }}</td>
        <td style="font-size:12px;">{{ orcamento.tipo }}</td>
        <td>R$ {{ orcamento.preco_total }}</td>
        <td > 
            {% if orcamento.status %}
            <img src="https://img.icons8.com/color/30/000000/verified-account.png">
            {% else %}
            <img src="https://img.icons8.com/color/30/000000/warning-shield.png">
            {% endif%}
        </td>
        <td>            
          {% if orcamento.status %}
            <a href="{% url 'oficina:detail_orcamento' orcamento.id %}"> <img src="https://img.icons8.com/dusk/30/000000/details-popup.png"> </a>
          {% else %}
            <a href="{% url 'oficina:novo_item' orcamento.id %}"><img src="https://img.icons8.com/color/30/000000/edit.png"></a>          
          {% endif %}
        </td>
      </tr>
      {% endfor %}       
    </table>
</div> 

{% endblock %}