ProjetoOficina/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oficina.urls')),
    path('relatorios/', include('relatorios.urls')),
    path('account/', include('django.contrib.auth.urls')),
    #url(r'^$',views.singIn),
    #url(r'^postsign/',views.postsign)
]

oficina/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views
app_name = 'oficina'
urlpatterns = [
    path('', views.index, name='index'),   
    path('register/', views.register, name='register'),
    path('produtos/', views.produtos, name='produtos'),
    path('produtos/new/', views.novo_produto, name='novo_produto'),
    path('produtos/delete/<int:id>/', views.apagar_produto, name='apagar_produto'),
    path('produtos/update/<int:id>/', views.atualizar_produto, name='atualizar_produto'),
    path('produtos/validar/', views.validar_descricao_produto, name='validar_descricao_produto'),
    #####################################
    path('fornecedores/', views.fornecedores, name='fornecedores'),
    path('fornecedores/new', views.novo_fornecedor, name='novo_fornecedor'),
    path('fornecedores/delete/<int:id>/', views.apagar_fornecedor, name='apagar_fornecedor'),
    path('fornecedores/edit/<int:id>/', views.atualizar_fornecedor, name='atualizar_fornecedor'),
    #######################################
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/new', views.novo_cliente, name='novo_cliente'),
    path('clientes/edit/<int:id>/', views.atualizar_cliente, name='atualizar_cliente'),
    path('clientes/delete/<int:id>/', views.apagar_cliente, name='apagar_cliente'),
    #######################################
    path('servicos/', views.servicos, name='servicos'),
    path('servicos/new', views.novo_servico, name='novo_servico'),
    path('servicos/delete/<int:id>/', views.apagar_servico, name='apagar_servico'),
    path('servicos/edit/<int:id>/', views.atualizar_servico, name='atualizar_servico'),
    #######################################
    path('vendas/', views.vendas, name='vendas'),
    path('vendas/detail/<int:orcamento_id>/', views.detail_orcamento, name='detail_orcamento'),    
    path('orcamentos/', views.orcamentos, name='orcamentos'),
    path('orcamentos/delete/<int:id>/', views.apagar_orcamento, name='apagar_orcamento'),
    path('orcamentos/edit/<int:id>/', views.atualizar_orcamento, name='atualizar_orcamento'),
    path('vendas/new', views.nova_venda, name='nova_venda'),    
    path('vendas/add/item/<int:orcamento_id>/', views.novo_item, name='novo_item'),
    path('vendas/delete/item/<int:orcamento_id>/<int:id>/', views.apagar_item, name='apagar_item'),
    path('vendas/edit/item/<int:orcamento_id>/<int:id>/', views.atualizar_item, name='atualizar_item'),
    path('vendas/finish/<int:orcamento_id>/', views.finalizar_venda, name='finalizar_venda'),
]

relatorios/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views
app_name = 'relatorios'
urlpatterns = [    
    path('lucro/', views.lucro, name='lucro'),
    path('itens/', views.itens_vendidos, name='itens_vendidos'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('pedidos/new/', views.novo_pedido, name="novo_pedido"),
    path('pedidos/produtos/', views.pedidos_estoque_baixo, name="pedidos_estoque_baixo"),
    path('pedidos/delete/<int:item_id>', views.apagar_pedido, name='apagar_pedido'),
    path('pedidos/edit/<int:id>', views.atualizar_pedido, name='atualizar_pedido'),
]   

oficina/forms.py
from django import forms
from .models import *
from django_select2.forms import *

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ["descricao","quantidade","valor_compra","valor_venda","categoria","codigo_fabrica","estoque_minimo"]
        widgets = {
            'categoria': Select2Widget,            
        }

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ["descricao", "cnpj", "observacao"]

class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ["logradouro","numero","bairro","cidade","estado","complemento"]

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nome","cpf","status"]

class TelefoneForm(forms.ModelForm):
    class Meta:
        model = Telefone
        fields = ["telefone"]

class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ["descricao","valor"]

class OrcamentoVendaForm(forms.ModelForm):
    class Meta:
        model = OrcamentoVenda
        fields = ["tipo","cliente","vendedor","status","desconto"]
        
class ItemVendaForm(forms.ModelForm):
    class Meta:
        model = ItemVenda
        fields = ("servico","produto","quantidade",)
        
    
class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ["orcamento"]

oficina/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from .models import *
from django.core.paginator import Paginator
from .forms import *
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.template import RequestContext
from django.forms import inlineformset_factory, modelformset_factory, formset_factory
from urllib.parse import urlencode
################ Produtos ###################
def index(request):
    '''lista_produtos = Produto.objects.order_by('id')
    data = {
        'lista_produtos' : lista_produtos,
    }
    return render(request, "oficina/index.html",data)'''
    return redirect('oficina:orcamentos')


def produtos(request,order=None):
    lista_produtos = Produto.objects.all().order_by('descricao')
    search = request.GET.get('search')
    if search:
        if search.isdigit():        
            lista_produtos = Produto.objects.filter(id=search)
        else:
            lista_produtos = Produto.objects.filter(descricao__icontains=search)
    
    
    '''paginator = Paginator(lista_produtos,4)
    page = request.GET.get('page')
    produtos = paginator.get_page(page)'''
    data = {        
        'produtos': lista_produtos,
    }
    return render(request, "oficina/produtos/produtos.html",data)
def apagar_produto(request,id):
    produto = get_object_or_404(Produto,pk=id)
    produto.delete()
    return redirect('oficina:produtos')


def atualizar_produto(request, id):
    produto = get_object_or_404(Produto,pk=id)
    form = ProdutoForm(instance=produto)
    if(request.method == 'POST'):
        form = ProdutoForm(request.POST, instance=produto)
        if(form.is_valid()):
                form.save()
                return redirect('oficina:produtos')
        else:
            return render(request, 'oficina/produtos/atualizarProduto.html', {'form': form, 'produto' : produto})
    elif(request.method == 'GET'):
        return render(request, 'oficina/produtos/atualizarProduto.html', {'form': form, 'produto' : produto})

def novo_produto(request):
    form = ProdutoForm()
    if(request.method == 'POST'):
        form = ProdutoForm(request.POST)
        if(form.is_valid()):                       
            try:
                form.save()   
                msg = "Produto Cadastrado com Sucesso !!!"   
                tipo = "alert alert-success"             
            except:
                msg = "Erro ao Cadastar !!!"
                tipo = "alert alert-danger"
            aux_form = ProdutoForm()
            data ={
                'form': aux_form,
                'alerta': True,
                'msg': msg,
                'tipo_alerta' : tipo                
            }            
            return render(request, 'oficina/produtos/novoProduto.html',data)                    
    elif(request.method == 'GET'):
        return render(request, 'oficina/produtos/novoProduto.html', {'form': form})


def validar_descricao_produto(request):
    descricao = request.GET.get('descricao', None)
    data = {
        'is_taken': Produto.objects.filter(descricao__iexact=descricao).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Existe um Produto Cadastrado com essa Descrição.'
    return JsonResponse(data)
############ Fornecedores ################
def fornecedores(request):
    fornecedores = Fornecedor.objects.all().order_by('descricao')    
    data = {
        'fornecedores': fornecedores,
    }
    return render(request, "oficina/fornecedores/fornecedores.html",data)

def novo_fornecedor(request):
    form = FornecedorForm()
    form_endereco = EnderecoForm()
    form_telefone = TelefoneForm()

    base_url = '/fornecedores/new'
    msg_sucesso = request.GET.get('msg_sucesso')
    msg_erro = request.GET.get('msg_erro')    
    data = {
        'form': form, 
        'form_endereco': form_endereco,
        'form_telefone':form_telefone,
        'msg_sucesso':msg_sucesso,
        'msg_erro':msg_erro,        
        }
    if (request.method == 'POST'):
        form = FornecedorForm(request.POST)
        form_endereco = EnderecoForm(request.POST)
        form_telefone = TelefoneForm(request.POST)
        if form.is_valid() and form_endereco.is_valid() and form_telefone.is_valid():                                                                                                
            try:
                form_endereco.save()
                form.instance.endereco = form_endereco.instance
                                        
                form_telefone.save()
                form.instance.telefone = form_telefone.instance

                form.save() 
                ###### Variaveis para mostrar na tela se foi cadastrado ou deu erro #######
                msg_sucesso = "Fornecedor Cadastrado com Sucesso !!!" 
                query_string = urlencode({'msg_sucesso': msg_sucesso})                 
            except:
                msg_erro = "Erro ao Cadastar !!!" 
                query_string = urlencode({'msg_erro': msg_erro}) 

            url = '{}?{}'.format(base_url,query_string)                                                   
            return redirect(url)  
    return render(request,'oficina/fornecedores/novoFornecedor.html',data)

def atualizar_fornecedor(request,id):
    fornecedor = get_object_or_404(Fornecedor,pk=id)    
    form = FornecedorForm(instance=fornecedor)

    endereco = get_object_or_404(Endereco,pk=fornecedor.get_endereco())
    form_endereco = EnderecoForm(instance=endereco)

    telefone = get_object_or_404(Telefone,pk=fornecedor.get_telefone())
    form_telefone = TelefoneForm(instance=telefone)

    base_url = '/fornecedores/edit/{}'.format(fornecedor.id)
    msg_sucesso = request.GET.get('msg_sucesso')
    msg_erro = request.GET.get('msg_erro')  
    data = {
        'form':form,
        'form_endereco':form_endereco,
        'form_telefone':form_telefone,
        'fornecedor':fornecedor,
        'msg_sucesso':msg_sucesso,
        'msg_erro':msg_erro,
        }
    if request.method == 'POST':
        form = FornecedorForm(request.POST, instance = fornecedor)
        form_endereco = EnderecoForm(request.POST,instance=endereco)
        form_telefone = TelefoneForm(request.POST,instance=telefone)
        if form.is_valid() and form_endereco.is_valid() and form_telefone.is_valid():
            try:
                form_endereco.save()
                form.instance.endereco = form_endereco.instance
                form_telefone.save()
                form.instance.telefone = form_telefone.instance
                form.save()
                msg_sucesso = "Fornecedor Atualizado com Sucesso !!!" 
                query_string = urlencode({'msg_sucesso': msg_sucesso})
            except:
                msg_erro = "Erro ao Atualizar !!!" 
                query_string = urlencode({'msg_erro': msg_erro}) 

            url = '{}?{}'.format(base_url,query_string)
            return redirect(url)
            
    elif request.method == 'GET':
        return render(request,'oficina/fornecedores/atualizarFornecedor.html',data)
def apagar_fornecedor(request,id):
    fornecedor = get_object_or_404(Fornecedor,pk=id)
    fornecedor.delete()
    return redirect('oficina:fornecedores')

################### Clientes ################################
def clientes(request):
    lista_clientes = Cliente.objects.all().order_by('nome')
    search = request.GET.get('search')
    if search:
        if search.isdigit():        
            lista_clientes = Cliente.objects.filter(id=search)
        else:
            lista_clientes = Cliente.objects.filter(nome__icontains=search)
        
    paginator = Paginator(lista_clientes,30)
    page = request.GET.get('page')
    clientes = paginator.get_page(page)
    data = {        
        'clientes': clientes,
        'name':'Cliente',
        'url':'oficina:clientes',
    }
    return render(request, "oficina/clientes/clientes.html",data)

def apagar_cliente(request,id):
    cliente = get_object_or_404(Cliente,pk=id)
    cliente.delete()
    return redirect('oficina:clientes')

def novo_cliente(request):
    form_cliente = ClienteForm()
    form_endereco = EnderecoForm()
    form_telefone = TelefoneForm()
    data = {'form_cliente':form_cliente, 'form_endereco':form_endereco, 'form_telefone':form_telefone}

    if (request.method == 'POST'):
        form_cliente = ClienteForm(request.POST)
        form_endereco = EnderecoForm(request.POST)
        form_telefone = TelefoneForm(request.POST)

        if form_cliente.is_valid() and form_endereco.is_valid() and form_telefone.is_valid():
            try:
                form_endereco.save()
                form_cliente.instance.endereco = form_endereco.instance

                form_telefone.save()
                form_cliente.instance.telefone = form_telefone.instance

                form_cliente.save()
                ###### Variaveis para mostrar na tela se foi cadastrado ou deu erro #######
                msg = "Cliente Cadastrado com Sucesso !!!"   
                tipo = "alert alert-success"
            except:
                msg = "Erro ao Cadastar !!!"
                tipo = "alert alert-danger"

            data = {
                'form_cliente':ClienteForm(), 
                'form_endereco':EnderecoForm(), 
                'form_telefone':TelefoneForm(),
                'alerta': True,
                'msg': msg,
                'tipo_alerta' : tipo
                }
            return render(request,'oficina/clientes/novoCliente.html',data) 
    elif request.method == 'GET':
        return render(request,'oficina/clientes/novoCliente.html',data)

def atualizar_cliente(request,id):
    cliente = get_object_or_404(Cliente,pk=id)
    form_cliente = ClienteForm(instance=cliente)

oficina/templates/oficina/clientes.html
{% extends 'oficina/base.html'%}
{% block title%}Clientes | Hugo MotoPeças{% endblock %}
{% block content %}
    {% for cliente in clientes %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">{{ cliente.nome }}</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="https://img.icons8.com/windows/25/000000/menu-2.png">                
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Opções para Clientes:</div>                    
                    <a class="dropdown-item" href="{% url 'oficina:atualizar_cliente' cliente.id %}">Editar</a>
                    <a class="dropdown-item" href="{% url 'oficina:apagar_cliente' cliente.id %}">Excluir</a>                    
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <div class="arrow" >
                <p>Código: {{ cliente.id }}</p>
            </div>
            <div class="arrow" >
                <p>CPF: {{ cliente.cpf }}</p>
            </div>
            <div class="arrow">
                <p>Telefone: {{ cliente.telefone.telefone }}</p>
            </div>

            <div class="arrow">
                <p>Endereço: {{ cliente.endereco.logradouro }}, Nº {{ cliente.endereco.numero }}, {{cliente.endereco.bairro}}, {{ cliente.endereco.cidade }} {{ cliente.endereco.estado }}, {{cliente.endereco.complemento}}</p>
            </div>
            <div class="arrow">
                <p>Status: {{cliente.status}}</p>
            </div>
            <div class="arrow">
                <p>Desde: {{cliente.created}}</p>
            </div>
            <div class="arrow">
                <p>Modificado: {{cliente.modified}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

oficina/templates/oficina/head.html
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Hugo Moto Peças</title>

  <!-- Custom fonts for this template-->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'oficina/vendor/fontawesome-free/css/all.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css">
  <!-- Custom styles for this template-->
  <link href="{% static 'oficina/css/sb-admin-2.min.css' %}" rel="stylesheet">

oficina/templates/oficina/menulateral.html
 <div id="wrapper">
    {% block content %}
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'oficina:index'%}">
        <div class="sidebar-brand-icon ">
        <img src="https://img.icons8.com/color/48/000000/motorbike-helmet.png">
        </div>
        <div class="sidebar-brand-text mx-3">Hugo Moto Peças<sup></sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Aba Vendas -->  
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVendas" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/dusk/25/000000/wallet.png">
          <span>Vendas</span>
        </a>
        <div id="collapseVendas" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para Vendas:</h6>
            <a class="collapse-item" href="{% url 'oficina:nova_venda'%}">
                <img src="https://img.icons8.com/cute-clipart/15/000000/plus-math.png">
                <span>Nova</span>
            </a>
            
            <a class="collapse-item" href="{% url 'oficina:orcamentos'%}">
                <img src="https://img.icons8.com/dusk/15/000000/time-machine.png">
                <span>Histórico</span>
            </a>
          </div>
        </div>
      </li>

      <!-- Aba Produtos -->  
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProdutos" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/dusk/25/000000/new-product.png">
          <span>Produtos</span>
        </a>
        <div id="collapseProdutos" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para produtos:</h6>
            <a class="collapse-item" href="{% url 'oficina:novo_produto' %}">
                <img src="https://img.icons8.com/cute-clipart/15/000000/plus-math.png">
                <span>Novo</span>
            </a>
            <a class="collapse-item" href="{% url 'oficina:produtos'%}">
                <img src="https://img.icons8.com/dusk/15/000000/show-property.png">
                <span>Detalhes</span>
            </a>
          </div>
        </div>
      </li>

      <!-- Aba Clientes -->  
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseClientes" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/dusk/25/000000/administrator-male.png">
          <span>Clientes</span>
        </a>
        <div id="collapseClientes" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para Clientes:</h6>
            <a class="collapse-item" href="{% url 'oficina:novo_cliente' %}">
                <img src="https://img.icons8.com/cute-clipart/15/000000/plus-math.png">
                <span>Novo</span>
            </a>
            <a class="collapse-item" href="{% url 'oficina:clientes'%}">
                <img src="https://img.icons8.com/dusk/15/000000/show-property.png">
                <span>Detalhes</span>
            </a>
          </div>
        </div>
      </li>

    <!-- Aba Fornecedores -->  
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFornecedores" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/dusk/25/000000/factory.png">
          <span>Fornecedores</span>
        </a>
        <div id="collapseFornecedores" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para Fornecedores:</h6>
            <a class="collapse-item" href="{% url 'oficina:novo_fornecedor' %}">
                <img src="https://img.icons8.com/cute-clipart/15/000000/plus-math.png">
                <span>Novo</span>
            </a>
            <a class="collapse-item" href="{% url 'oficina:fornecedores' %}">
                <img src="https://img.icons8.com/dusk/15/000000/show-property.png">
                <span>Detalhes</span>
            </a>
          </div>
        </div>
      </li>
      <!-- Aba Serviços -->  
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseServicos" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/color/25/000000/full-tool-storage-box-.png">
          <span>Serviços</span>
        </a>
        <div id="collapseServicos" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para Serviços:</h6>
            <a class="collapse-item" href="{% url 'oficina:novo_servico' %}">
                <img src="https://img.icons8.com/cute-clipart/15/000000/plus-math.png">
                <span>Novo</span>
            </a>
            <a class="collapse-item" href="{% url 'oficina:servicos' %}">
                <img src="https://img.icons8.com/dusk/15/000000/show-property.png">
                <span>Detalhes</span>
            </a>
          </div>
        </div>
      </li>
    <!-- Aba de relatorios -->
      <!-- Divider -->
      <hr class="sidebar-divider">
      
      <!-- Heading -->
      <div class="sidebar-heading">
        Relatórios
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePedidos" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/color/25/000000/attendance-mark.png">
          <span>Pedidos</span>
        </a>
        <div id="collapsePedidos" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para pedidos:</h6>
            <a class="collapse-item" href="{% url 'relatorios:novo_pedido' %}">Novo Item</a>
            <a class="collapse-item" href="{% url 'relatorios:pedidos' %}">Itens a Comprar</a>            
            <a class="collapse-item" href="{% url 'relatorios:pedidos_estoque_baixo' %}">Itens com Estoque Baixo</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFinanceiro" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/color/25/000000/money-bag.png">
          <span>Financeiro</span>
        </a>
        <div id="collapseFinanceiro" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Opções para relatórios:</h6>
            <a class="collapse-item" href="{% url 'relatorios:lucro' %}">Lucro</a>
            <a class="collapse-item" href="#">Total Vendido</a>
            <a class="collapse-item" href="#">A Receber</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEstoque" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/color/25/000000/open-box.png">
          <span>Estoque</span>
        </a>
        <div id="collapseEstoque" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="{% url 'relatorios:itens_vendidos'%}">Itens Vendidos</a>
            <a class="collapse-item" href="#">Cards</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Administrativo
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsuarios" aria-expanded="true" aria-controls="collapseTwo">
          <img src="https://img.icons8.com/dusk/25/000000/google-groups.png">
          <span>Usuários</span>
        </a>
        <div id="collapseUsuarios" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="#">Buttons</a>
            <a class="collapse-item" href="#">Cards</a>
          </div>
        </div>
      </li>
          
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
    </ul>
{% endblock %}
</div>

oficina/templates/oficina/msg.html
{% if alerta %}
    <div class="{{tipo_alerta}}" role="alert" id="msg">
        {{msg}}
    </div>            
{% endif %}
<script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function(){ 
            setTimeout(function() {
                $("#msg").fadeOut().empty();
            }, 2000);
        }, false);        
    </script>

oficina/templates/oficina/register.html
{% extends 'oficina/base.html' %}
{% block title %}Crie um novo Usuário{% endblock %}
{% block content %}
{% load bootstrap%}
    <div class="container">
        
        <form action="." method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <input class="btn btn-primary" type="submit" value="Registrar">
        </form>
    </div>
{% endblock %}